### ISSUE TITLE
This application crashes on graalvm-ce-19.2.0

### ISSUE THREAD

**Issue by pavlomorozov** [adikm/java-javascript-graalvm#1]
It seems like java script cannot access object properties and methods

> Hello from the project
> I will welcome you 3 times.
> Welcome
> Welcome
> Welcome
> jsVariable
> undefined
> Exception in thread "main" TypeError: invokeMember (call) on JavaObject[net.amarszalek.javapolyglot.Phone@18df8434 (net.amarszalek.javapolyglot.Phone)] failed due to: Unknown identifier: call
> 	at <js> :program(Unnamed:1:0-20)
> 	at org.graalvm.polyglot.Context.eval(Context.java:370)
> 	at net.amarszalek.javapolyglot.Application.runScript(Application.java:46)
> 	at net.amarszalek.javapolyglot.Application.accessJavaObjectFromScript(Application.java:42)
> 	at net.amarszalek.javapolyglot.Application.main(Application.java:12)

It could be nice to get this code updated as soon as it touches quite an interesting functionality available in Nashorn but not in GraalVM.

**Comment by adikm** [comment]
Hi Pavel, I'll look into this and try to get back to you as soon as possible :)

**Comment by pavlomorozov** [comment]
Hi! I found the problem with Context. Use this instead:

`Context jsContext = Context.newBuilder("js").allowHostAccess(HostAccess.ALL).build();`

This makes it works. Also you can instantiate Context in try-with-resources clause and you will not need `jsContext.close();` then.

Have a good luck!
